# Generated by Django 3.2.7 on 2021-12-01 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('preco', models.FloatField()),
                ('duracao', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Horarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to=settings.AUTH_USER_MODEL)),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='estabelecimentos.servico')),
            ],
            options={
                'verbose_name': 'Horarios',
                'verbose_name_plural': 'Horarios',
            },
        ),
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250, verbose_name='Nome')),
                ('cnpj', models.CharField(max_length=25, verbose_name='CNPJ')),
                ('cidade', models.CharField(max_length=250, verbose_name='Cidade')),
                ('bairro', models.CharField(max_length=250, verbose_name='bairro')),
                ('rua', models.CharField(max_length=250, verbose_name='Rua')),
                ('numero', models.CharField(max_length=250, verbose_name='Numero')),
                ('cep', models.CharField(max_length=15, verbose_name='CEP')),
                ('horario_inicio', models.TimeField()),
                ('horario_final', models.TimeField()),
                ('telefone', models.CharField(max_length=50, verbose_name='CEP')),
                ('latitude', models.CharField(max_length=100, verbose_name='Latitude')),
                ('longitude', models.CharField(max_length=100, verbose_name='Longitude')),
                ('data_cadastro', models.DateField(auto_now_add=True, verbose_name='Data cadastro')),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estabelecimentos', to='users.proprietario')),
            ],
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estabelecimento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='estabelecimentos.estabelecimento')),
                ('horarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='estabelecimentos.horarios')),
            ],
        ),
    ]
