# Generated by Django 3.2.7 on 2021-10-20 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250, verbose_name='Nome')),
                ('cidade', models.CharField(max_length=250, verbose_name='Cidade')),
                ('bairro', models.CharField(max_length=250, verbose_name='bairro')),
                ('rua', models.CharField(max_length=250, verbose_name='Rua')),
                ('numero', models.CharField(max_length=250, verbose_name='Numero')),
                ('cep', models.CharField(max_length=15, verbose_name='CEP')),
                ('telefone', models.CharField(max_length=50, verbose_name='CEP')),
                ('latitude', models.CharField(max_length=100, verbose_name='Latitude')),
                ('longitude', models.CharField(max_length=100, verbose_name='Longitude')),
                ('data_cadastro', models.DateField(auto_now_add=True, verbose_name='Data cadastro')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estabelecimentos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
