# Generated by Django 3.2.7 on 2021-12-02 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estabelecimentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='estabelecimento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='estabelecimentos.estabelecimento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agenda',
            name='estabelecimento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agenda', to='estabelecimentos.estabelecimento'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='horarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda', to='estabelecimentos.horarios'),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='estabelecimentos.servico'),
        ),
    ]
