# Generated by Django 3.2.7 on 2021-12-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estabelecimentos', '0003_auto_20211202_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horarios',
            name='fim',
        ),
        migrations.RemoveField(
            model_name='horarios',
            name='inicio',
        ),
        migrations.AddField(
            model_name='horarios',
            name='data',
            field=models.DateField(default='2021-12-12'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horarios',
            name='horario',
            field=models.TimeField(default='12:20'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horarios',
            name='horario_termino',
            field=models.TimeField(default='12:50'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servico',
            name='qtd_atendentes',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
